spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /api/customers/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /api/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
